In [2]:
import pandas as pd
data=pd.read_csv("first_data.csv")

In [36]:
data.sample(40)

Unnamed: 0.1  Unnamed: 0      gbifID  \
28256        100386      165970  1319879688   
4519          18652       27206  1272066729   
22187         76568      123363  2515565909   
14990         53277       84845   477944030   
18038         65866      102951  1259233000   
25899         91426      152925   351385959   
5286          20795       30466  2513248687   
1517           7088       11006  1319683810   
11590         43530       70823  1260336081   
9102          33603       54301  2513094029   
118             429         645   477234348   
35381        123531      203560  2513208874   
6693          24256       37143  1315155867   
24224         84648      135469  1318587144   
5986          22675       33865  1932878940   
31636        111725      183938  2513115210   
18527         67359      104615  1258237338   
18172         66259      103388  1257807397   
17135         64045       99926  2856207428   
16682         62663       98266  1927841600   
5945          22634       33823  1932882700   
17578         64595      100478  3710567045   
11174         42340       69285  1320649831   
11735         43969       71303  1259191556   
5705          22335       33397  1055368598   
13441         49523       78997  1890899839   
18644         67756      105278  1056366124   
3593          13789       19297  1259858475   
30404        107871      177334  1258683979   
29300        103296      169166   657982063   
12658         46693       74362  1257673368   
926            4425        6813  1929339888   
29574        104828      172576      607734   
14021         50109       79615  1890919738   
21028         72701      116488  1325706916   
25944         91699      153306  1998549598   
27748         98988      164450   911587888   
3735          14451       20641   775299594   
21019         72691      116478  1325706952   
13717         49801       79286  1934702130   

                                 datasetKey   kingdom         phylum  \
28256  821cc27a-e3bb-4bc5-ac34-89ada245069d   Plantae   Tracheophyta   
4519   4bfac3ea-8763-4f4b-a71a-76a6f5f243d3  Animalia     Arthropoda   
22187  15f819bd-6612-4447-854b-14d12ee1022d   Plantae   Tracheophyta   
14990  4bfac3ea-8763-4f4b-a71a-76a6f5f243d3  Animalia     Arthropoda   
18038  7bd65a7a-f762-11e1-a439-00145eb45e9a   Plantae   Tracheophyta   
25899  854bc2fc-f762-11e1-a439-00145eb45e9a  Animalia        Bryozoa   
5286   15f819bd-6612-4447-854b-14d12ee1022d   Plantae   Tracheophyta   
1517   821cc27a-e3bb-4bc5-ac34-89ada245069d   Plantae   Tracheophyta   
11590  7bd65a7a-f762-11e1-a439-00145eb45e9a   Plantae   Tracheophyta   
9102   15f819bd-6612-4447-854b-14d12ee1022d   Plantae   Tracheophyta   
118    4bfac3ea-8763-4f4b-a71a-76a6f5f243d3  Animalia       Mollusca   
35381  15f819bd-6612-4447-854b-14d12ee1022d   Plantae   Tracheophyta   
6693   56fe0b98-95e1-4544-b398-fa7cebf18598  Animalia     Arthropoda   
24224  821cc27a-e3bb-4bc5-ac34-89ada245069d   Plantae   Tracheophyta   
5986   9b73f44e-bbe1-4fd1-a7a9-c96c38dcf884   Plantae   Tracheophyta   
31636  15f819bd-6612-4447-854b-14d12ee1022d   Plantae   Tracheophyta   
18527  7bd65a7a-f762-11e1-a439-00145eb45e9a   Plantae   Tracheophyta   
18172  7bd65a7a-f762-11e1-a439-00145eb45e9a   Plantae   Tracheophyta   
17135  c001a28f-6f37-40e9-8e34-e0ada1772e4d  Animalia     Arthropoda   
16682  d415c253-4d61-4459-9d25-4015b9084fb0   Plantae   Tracheophyta   
5945   9b73f44e-bbe1-4fd1-a7a9-c96c38dcf884   Plantae   Tracheophyta   
17578  c001a28f-6f37-40e9-8e34-e0ada1772e4d  Animalia     Arthropoda   
11174  821cc27a-e3bb-4bc5-ac34-89ada245069d   Plantae   Tracheophyta   
11735  7bd65a7a-f762-11e1-a439-00145eb45e9a   Plantae   Tracheophyta   
5705   7e380070-f762-11e1-a439-00145eb45e9a  Animalia  Echinodermata   
13441  18da9e5d-8966-4893-bf70-b3911152d991   Plantae   Tracheophyta   
18644  7e380070-f762-11e1-a439-00145eb45e9a   Plantae   Tracheophyta   
3593   7bd65a7a-f762-11e1-a439-00145eb45e9a   Plantae   Tracheo

In [37]:
data.shape

(36510, 98)

In [38]:
plantae=data.copy()
plantae=plantae[plantae['kingdom']=='Plantae']
plantae.shape

(19127, 98)

In [39]:
preprocessed=plantae.copy()
data_strings=preprocessed[['Unnamed: 0.1', 'Unnamed: 0','gbifID','datasetKey','kingdom',
       'phylum','class','order','family','genus','species',
       'scientificName','verbatimScientificName','countryCode','locality',
       'stateProvince','decimalLatitude', 'decimalLongitude','year']]
preprocessed=preprocessed.drop(columns=['Unnamed: 0.1', 'Unnamed: 0', 'gbifID', 'datasetKey', 'kingdom',
       'phylum', 'class', 'order', 'family', 'genus', 'species',
       'scientificName', 'verbatimScientificName', 'countryCode', 'locality',
       'stateProvince', 'decimalLatitude', 'decimalLongitude', 'year'])

In [40]:
preprocessed

b1         b2        b3         b4         b5        b6  \
98     26.766668   7.650000  0.714953  10.700003  22.200001  0.597681   
99     27.016665   8.541667  0.813492  10.500000  22.400000  0.538259   
100    26.766668   7.650000  0.714953  10.700003  22.200001  0.597681   
101    26.766668   7.650000  0.714953  10.700003  22.200001  0.597681   
102    25.558334   8.583333  0.686667  12.500000  20.700001  0.490677   
...          ...        ...       ...        ...        ...       ...   
36505  25.625002   9.433333  0.731266  12.900000  20.000000  0.696569   
36506  22.033333  10.058333  0.874638  11.500000  16.100000  0.426875   
36507   7.466667  12.141666  0.304302  39.900002 -14.200000  9.608792   
36508  26.725000   9.733334  0.760417  12.800001  20.600000  0.534049   
36509  25.066666  12.450000  0.773292  16.099998  16.100000  0.954230   

              b7          b8           b9         b10  ...  soc_15-30  \
98     32.200001  189.500000   841.500000   38.200001  ...       95.0   
99     32.799999  215.600006   721.100037   19.500000  ...       98.0   
100    32.200001  189.500000   841.500000   38.200001  ...       95.0   
101    32.200001  189.500000   841.500000   38.200001  ...       95.0   
102    30.900000  540.799988   938.600037  174.800003  ...      223.0   
...          ...         ...          ...         ...  ...        ...   
36505  32.100002  557.700012   873.500000  183.300003  ...      386.0   
36506  28.300001  638.100037  1063.000000  140.000000  ...      100.0   
36507  27.700001  209.200012   296.700012   32.500000  ...      192.0   
36508  32.299999  544.599976   825.500000  170.699997  ...      157.0   
36509  32.299999  166.199997   501.000000   23.200001  ...      108.0   

       soc_30-60  soc_60-100  soc_100-200  ocd_0-5  ocd_5-15  ocd_15-30  \
98         103.0        68.0         63.0    327.0     240.0      200.0   
99          57.0        49.0         45.0    286.0     220.0      134.0   
100        103.0        68.0         63.0    327.0     240.0      200.0   
101        103.0        68.0         63.0    327.0     240.0      200.0   
102        216.0       221.0        312.0    417.0     282.0      158.0   
...          ...         ...          ...      ...       ...        ...   
36505      370.0       343.0        413.0    626.0     289.0      158.0   
36506       52.0        42.0         32.0    393.0     263.0      169.0   
36507      140.0       102.0        140.0    429.0     292.0      226.0   
36508       79.0        51.0         43.0    338.0     290.0      206.0   
36509      113.0        90.0         91.0    284.0     248.0      151.0   

       ocd_30-60  ocd_60-100  ocd_100-200  
98         156.0        91.0        100.0  
99          79.0        56.0         36.0  
100        156.0        91.0        100.0  
101        156.0        91.0        100.0  
102         93.0        57.0         33.0  
...          ...         ...          ...  
36505       97.0        66.0         31.0  
36506       97.0        55.0         39.0  
36507      168.0       170.0        199.0  
36508       79.0        65.0         29.0  
36509       95.0        59.0         44.0  

[19127 rows x 79 columns]

In [44]:
from sklearn.preprocessing import Normalizer
scaler= Normalizer()
scaler = Normalizer().fit(preprocessed)  # fit does nothing.
preprocessed=scaler.transform(preprocessed)

array([[0.00858409, 0.00245336, 0.00022929, ..., 0.0500293 , 0.02918376,
        0.03207006],
       [0.0091294 , 0.00288638, 0.00027489, ..., 0.02669548, 0.01892338,
        0.01216503],
       [0.00858409, 0.00245336, 0.00022929, ..., 0.0500293 , 0.02918376,
        0.03207006],
       ...,
       [0.00335017, 0.00544776, 0.00013654, ..., 0.07537876, 0.07627613,
        0.08928794],
       [0.00732794, 0.00266886, 0.0002085 , ..., 0.02166164, 0.01782287,
        0.00795174],
       [0.0098158 , 0.00487527, 0.00030281, ..., 0.03720085, 0.02310369,
        0.01722987]])

In [46]:
from sklearn.neighbors import NearestNeighbors
import numpy as np
nrst_neigh = NearestNeighbors(n_neighbors = 10, algorithm='ball_tree')
nrst_neigh.fit(preprocessed)
distances, indices = nrst_neigh.kneighbors(preprocessed)
indices
distances
nrst_neigh.kneighbors_graph(preprocessed).toarray()

array([[1., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
indices.shape

(36510, 10)

In [20]:
distances.shape

(36510, 10)

In [21]:
preprocessed.shape

(36510, 79)

In [48]:
indices[300]

array([ 1198,   300,  2906,   229, 16342,  4349, 13779, 16357, 16616,
        8965])

In [51]:
## not good, we can see it recommends plants that are very close together geographically
print(data_strings.iloc[300].loc['species'], data_strings.iloc[300].loc['decimalLatitude'], data_strings.iloc[300].loc['decimalLongitude'] )
print(data_strings.iloc[1198].loc['species'], data_strings.iloc[1198].loc['decimalLatitude'], data_strings.iloc[1198].loc['decimalLongitude'])
print(data_strings.iloc[2906].loc['species'], data_strings.iloc[2906].loc['decimalLatitude'], data_strings.iloc[2906].loc['decimalLongitude'])
print(data_strings.iloc[229].loc['species'], data_strings.iloc[229].loc['decimalLatitude'], data_strings.iloc[229].loc['decimalLongitude'])
print(data_strings.iloc[16342].loc['species'], data_strings.iloc[16342].loc['decimalLatitude'], data_strings.iloc[16342].loc['decimalLongitude'])
print(data_strings.iloc[4349].loc['species'], data_strings.iloc[4349].loc['decimalLatitude'], data_strings.iloc[4349].loc['decimalLongitude'])
print(data_strings.iloc[13779].loc['species'], data_strings.iloc[13779].loc['decimalLatitude'], data_strings.iloc[13779].loc['decimalLongitude'])
print(data_strings.iloc[16357].loc['species'], data_strings.iloc[16357].loc['decimalLatitude'], data_strings.iloc[16357].loc['decimalLongitude'])
print(data_strings.iloc[16616].loc['species'], data_strings.iloc[16616].loc['decimalLatitude'], data_strings.iloc[16616].loc['decimalLongitude'])
print(data_strings.iloc[8965].loc['species'], data_strings.iloc[8965].loc['decimalLatitude'], data_strings.iloc[8965].loc['decimalLongitude'])

Amphilophium rodriguesii -3.1052811267605995 -60.02620538987911
Amphilophium reticulatum -3.116667 -60.033333
Jacaranda copaia -2.883333 -59.97
Aspidosperma excelsum -3.001413 -60.05805
Lorostemon bombaciflorus -3.113333 -60.025278
Erisma gracile -3.113333 -60.025278
Ravenia biramosa -3.113333 -60.025278
Mollia nitida -3.113333 -60.025278
Iryanthera coriacea -3.113333 -60.025278
Styrax glabratus -2.95487 -59.928188


In [71]:
## We try KMeansClustering

from sklearn.cluster import KMeans

kmean=KMeans(n_clusters=50, max_iter=300, tol=0.0001, verbose=0)

kmean=kmean.fit(preprocessed)

kmean.labels_
# kmean.predict
# kmeans.cluster_centers_



array([33, 15, 33, ..., 16,  0, 42], dtype=int32)

In [72]:
kmean.labels_[300]

33

In [73]:
f=[]
for i in range(len(kmean.labels_)):
    if kmean.labels_[i]==kmean.labels_[300]:
        f.append(i)

In [57]:
f

[0,
 2,
 3,
 5,
 66,
 132,
 229,
 300,
 1198,
 1542,
 2138,
 2378,
 2697,
 2704,
 2730,
 2765,
 2766,
 2773,
 2774,
 2798,
 2828,
 2829,
 2841,
 2842,
 2858,
 2861,
 2873,
 2885,
 2886,
 2906,
 2913,
 2914,
 2928,
 2951,
 2971,
 2974,
 2976,
 2979,
 2994,
 2995,
 2996,
 3007,
 3063,
 3192,
 4096,
 4349,
 4706,
 7467,
 7536,
 7548,
 8928,
 8955,
 8965,
 9470,
 9548,
 11446,
 11755,
 12189,
 12202,
 12382,
 13297,
 13779,
 13863,
 14484,
 14510,
 16342,
 16357,
 16420,
 16615,
 16616,
 16647,
 16648,
 17368,
 17445,
 17849,
 18032,
 18947,
 19086]

In [58]:
print(data_strings.iloc[300].loc['species'], data_strings.iloc[300].loc['decimalLatitude'], data_strings.iloc[300].loc['decimalLongitude'] )
print(data_strings.iloc[8928].loc['species'], data_strings.iloc[8928].loc['decimalLatitude'], data_strings.iloc[8928].loc['decimalLongitude'])
print(data_strings.iloc[11446].loc['species'], data_strings.iloc[11446].loc['decimalLatitude'], data_strings.iloc[11446].loc['decimalLongitude'])
print(data_strings.iloc[11755].loc['species'], data_strings.iloc[11755].loc['decimalLatitude'], data_strings.iloc[11755].loc['decimalLongitude'])
print(data_strings.iloc[12189].loc['species'], data_strings.iloc[12189].loc['decimalLatitude'], data_strings.iloc[12189].loc['decimalLongitude'])
print(data_strings.iloc[12202].loc['species'], data_strings.iloc[12202].loc['decimalLatitude'], data_strings.iloc[12202].loc['decimalLongitude'])
print(data_strings.iloc[12382].loc['species'], data_strings.iloc[12382].loc['decimalLatitude'], data_strings.iloc[12382].loc['decimalLongitude'])
print(data_strings.iloc[13297].loc['species'], data_strings.iloc[13297].loc['decimalLatitude'], data_strings.iloc[13297].loc['decimalLongitude'])
print(data_strings.iloc[13779].loc['species'], data_strings.iloc[13779].loc['decimalLatitude'], data_strings.iloc[13779].loc['decimalLongitude'])
print(data_strings.iloc[16616].loc['species'], data_strings.iloc[16616].loc['decimalLatitude'], data_strings.iloc[16616].loc['decimalLongitude'])

Amphilophium rodriguesii -3.1052811267605995 -60.02620538987911
Eschweilera rodriguesiana -2.984139 -60.051331
Vernonia gilbertii 9.4 35.583333
Eschweilera atropetiolata -2.95487 -59.928188
Lecythis prancei -2.95487 -59.928188
Ocotea nigrescens -2.95487 -59.928188
Vantanea micrantha -2.874325 -60.096261
Aniba ferrea -2.95487 -59.928188
Ravenia biramosa -3.113333 -60.025278
Iryanthera coriacea -3.113333 -60.025278


In [74]:
df=pd.DataFrame(f)

In [89]:
df['species']=[data_strings.iloc[i].loc['species']for i in f]
df['lon']=[data_strings.iloc[i].loc['decimalLongitude']for i in f]
df['lat']=[data_strings.iloc[i].loc['decimalLatitude']for i in f]
df['lon_ref']=[data_strings.iloc[300].loc['decimalLongitude']for i in f]
df['lat_ref']=[data_strings.iloc[300].loc['decimalLatitude'] for i in f]
df['lon_dif']=(df['lon_ref']-df['lon'])**2
df['lat_dif']=(df['lat_ref']-df['lat'])**2
df['sum']=df['lon_dif']+df['lat_dif']

In [91]:
g=df.copy()
g=g.sort_values(by=['sum'])
g

0                      species         lon        lat    lon_ref  \
31     300     Amphilophium rodriguesii  -60.026205  -3.105281 -60.026205   
0        0        Pictolejeunea sprucei  -60.025000  -3.101944 -60.026205   
1        2        Syrrhopodon annotinus  -60.025000  -3.101944 -60.026205   
2        3  Octoblepharum leucobryoides  -60.025000  -3.101944 -60.026205   
3        5        Syrrhopodon annotinus  -60.025000  -3.101944 -60.026205   
..     ...                          ...         ...        ...        ...   
382  13904           Syzygium germainii   20.866667  -0.216667 -60.026205   
282  11446           Vernonia gilbertii   35.583333   9.400000 -60.026205   
276  11171               Musa itinerans  113.767767  23.647000 -60.026205   
273  10542               Musa itinerans  113.774883  23.649383 -60.026205   
155   3973      Scopelophila cataractae  120.947689  23.924500 -60.026205   

      lat_ref       lon_dif     lat_dif           sum  
31  -3.105281      0.000000    0.000000      0.000000  
0   -3.105281      0.000001    0.000011      0.000013  
1   -3.105281      0.000001    0.000011      0.000013  
2   -3.105281      0.000001    0.000011      0.000013  
3   -3.105281      0.000001    0.000011      0.000013  
..        ...           ...         ...           ...  
382 -3.105281   6543.656803    8.344092   6552.000895  
282 -3.105281   9141.183831  156.382056   9297.565887  
276 -3.105281  30204.344839  715.684545  30920.029385  
273 -3.105281  30206.818326  715.812053  30922.630378  
155 -3.105281  32751.550451  730.609068  33482.159518  

[541 rows x 9 columns]

In [63]:
data_strings.iloc[18947].loc['species']

'Inga suberosa'